spring.application.name=CrimeAi

server.port=8080


# ===============================
# PostgreSQL Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/crime_ai
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Neo4j Configuration
# ===============================

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=7447025748